name: recipe_from_fridge
description: Offline recipe suggester based on available ingredients
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  collection: ^1.18.0


  flutter_animate: ^4.5.0

  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/recipes.json
    - assets/substitutions.json